apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lvm
  labels:
    app: deployment-lvm
spec:
  selector:
    matchLabels:
      app: deployment-lvm
  template:
    metadata:
      labels:
        app: deployment-lvm
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: busybox
        image: registry-qcc.quantil.com/public/busybox:latest
        command: ["sleep","3600"]
        volumeMounts:
          - name: lvm-pvc
            mountPath: "/data"
      volumes:
        - name: lvm-pvc
          persistentVolumeClaim:
            claimName: lvm-pvc