apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm-striping
provisioner: lvmplugin.csi.quantil.com
parameters:
    vgName: qcc
    fsType: ext4
    pvType: localdisk
    lvmType: thinpool
    nodeAffinity: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer