apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm-striping
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
    vgName: qcc
    fsType: ext4
    pvType: localdisk
    lvmType: linear
    nodeAffinity: "false"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer